import { chromium, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { PNG } from 'pngjs';
fs.mkdirSync('work/native-quality',{recursive:true});
const browser=await chromium.connectOverCDP('http://127.0.0.1:9335');
const page=browser.contexts()[0].pages().find(p=>p.url().includes('tauri.localhost'));
assert.ok(page,'Native release WebView must be present');
page.setDefaultTimeout(90000);
page.on('crash',()=>console.error('Native page crashed'));
const checkpoint = stage => console.log(new Date().toISOString(), stage);
const errors=[], requests=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
page.on('request',r=>requests.push(r.url()));
try {
 await page.waitForFunction(()=>document.querySelector('[data-testid=viewport]')?.dataset.rendererState==='ready');
 const runtime=await page.evaluate(()=>window.__TAURI_INTERNALS__.invoke('runtime_info',{}));
 assert.equal(runtime.appVersion,'0.1.5');
 await expect(page.getByRole('combobox',{name:'Режим просмотра'})).toHaveValue('detailed');
 await page.getByRole('combobox',{name:'Край',exact:true}).selectOption('stitched');
 await page.getByRole('button',{name:'Применить ткань Poly Haven',exact:true}).click();
 await expect(page.getByText('Ткань Poly Haven применена. Карты будут сохранены внутри проекта.',{exact:true})).toBeVisible({timeout:30000});
 const projectPath=path.resolve('work/quality-ui/polyhaven.matvision'), savedPath=path.resolve('work/native-quality/portable.matvision');
 const portable=await page.evaluate(async({projectPath,savedPath})=>{
  const api=window.__TAURI_INTERNALS__;
  const contents=await api.invoke('open_project',{path:projectPath});
  await api.invoke('save_project',{contents,path:savedPath});
  return (await api.invoke('open_project',{path:savedPath}))===contents;
 },{projectPath,savedPath});
 assert.ok(portable); checkpoint('Native project roundtrip passed');
 await page.getByRole('button',{name:'Фото',exact:true}).click();
 await page.getByRole('combobox',{name:'Проходы фото'}).selectOption('128');
 await page.getByRole('button',{name:'Рассчитать фото',exact:true}).click();
 await expect(page.getByText(/Фото готово\./)).toBeVisible({timeout:600000});
 checkpoint('Native photo completed 128 samples');
 const pngPath=path.resolve('work/native-quality/photo-1920.png');
 const photo=await page.evaluate(async pngPath=>{
  const canvas=document.querySelector('.photo-canvas canvas'),gl=canvas.getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');
  const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));
  const bytes=new Uint8Array(await blob.arrayBuffer());
  const encoded=btoa(Array.from(new TextEncoder().encode(pngPath),b=>String.fromCharCode(b)).join(''));
  await window.__TAURI_INTERNALS__.invoke('save_png',bytes,{headers:{'x-matvision-path':encoded}});
  return {width:canvas.width,height:canvas.height,adapter:gl.getParameter(ext.UNMASKED_RENDERER_WEBGL)};
 },pngPath);
 assert.equal(Math.max(photo.width,photo.height),1920);
 const image=PNG.sync.read(fs.readFileSync(pngPath));
 let red=0,green=0;for(let y=Math.floor(image.height*.45);y<image.height*.55;y++)for(let x=Math.floor(image.width*.45);x<image.width*.55;x++){let i=(y*image.width+x)*4;red+=image.data[i];green+=image.data[i+1];}
 assert.ok(green>red*1.15,'Native photo must preserve teal print');
 fs.writeFileSync('work/native-quality/photo-checks.json',JSON.stringify({runtime,portable,photo,colourPreserved:true},null,2));
 checkpoint('Native PNG saved and colour checked');
 await page.screenshot({path:'work/native-quality/photo-interface.png'});
 await page.getByRole('button',{name:'Вернуться в студию',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 checkpoint('Returned to studio');
 await page.getByRole('button',{name:'Фото',exact:true}).click();
 await page.getByRole('button',{name:'Рассчитать фото',exact:true}).click();
 await page.getByRole('button',{name:'Отменить и вернуться',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Фото',exact:true}).click();
 await expect(page.getByRole('button',{name:'Рассчитать фото',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Вернуться в студию',exact:true}).click();
 checkpoint('Cancel and reopen passed');
 await page.getByRole('button',{name:'Макро ткани',exact:true}).click();await page.waitForTimeout(1500);
 await page.screenshot({path:'work/native-quality/macro-interface.png'});
 assert.deepEqual(errors,[]);
 assert.ok(requests.every(url=>url.startsWith('http://tauri.localhost/')||url.startsWith('http://ipc.localhost/')||url.startsWith('ipc:')||url.startsWith('blob:')||url.startsWith('data:')),'Release assets must remain local');
 const report={runtime,portable,photo,returnToStudio:true,cancelAndReopen:true,localRequestsOnly:true,errors};fs.writeFileSync('work/native-quality/checks.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
} finally {await browser.close();}
