import { chromium, expect } from '@playwright/test';
import { PNG } from 'pngjs';
import fs from 'node:fs';
import assert from 'node:assert/strict';

fs.mkdirSync('work/realism-ui', { recursive: true });
const browser = await chromium.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
try {
  await page.goto('http://127.0.0.1:1420');
  await page.waitForFunction(() => document.querySelector('[data-testid=viewport]')?.dataset.rendererState === 'ready');
  await page.getByRole('combobox', { name: 'Край', exact: true }).selectOption('stitched');
  await page.getByRole('combobox', { name: 'Режим просмотра' }).selectOption('detailed');
  await page.locator('.realism-controls summary').click();
  const normal = new PNG({ width: 64, height: 64 });
  for (let i = 0; i < normal.data.length; i += 4) normal.data.set([128, 128, 255, 255], i);
  const chooserPromise = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Микрорельеф Выбрать карту…' }).click();
  await (await chooserPromise).setFiles({ name: 'sample-normal.png', mimeType: 'image/png', buffer: PNG.sync.write(normal) });
  await expect(page.locator('.material-map-row').filter({ hasText: 'sample-normal.png' })).toBeVisible();
  await expect(page.getByText('Подготовка материала…', { exact: true })).toHaveCount(0);
  await page.getByRole('spinbutton', { name: 'Размер материала, мм' }).fill('75');
  await page.getByRole('combobox', { name: 'Тип карты микрорельефа' }).selectOption('directx');
  const savePromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Сохранить проект', exact: true }).click();
  const saved = await savePromise;
  await saved.saveAs('work/realism-ui/portable.matvision');
  const doc = JSON.parse(fs.readFileSync('work/realism-ui/portable.matvision', 'utf8'));
  assert.equal(doc.version, 2);
  assert.equal(doc.state.materials.fabric.tileMm, 75);
  assert.equal(doc.state.materials.fabric.normalY, 'directx');
  assert.equal(doc.state.materials.fabric.maps.normal.name, 'sample-normal.png');
  await page.getByRole('button', { name: 'Удалить карту: Микрорельеф' }).click();
  await expect(page.locator('.material-map-row').filter({ hasText: 'sample-normal.png' })).toHaveCount(0);
  const projectChooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: 'Открыть проект', exact: true }).click();
  await (await projectChooser).setFiles('work/realism-ui/portable.matvision');
  await expect(page.locator('.material-map-row').filter({ hasText: 'sample-normal.png' })).toBeVisible();
  await expect(page.getByRole('spinbutton', { name: 'Размер материала, мм' })).toHaveValue('75');
  await page.getByRole('button', { name: 'Удалить карту: Микрорельеф' }).click();
  await expect(page.locator('.material-map-row').filter({ hasText: 'sample-normal.png' })).toHaveCount(0);
  await page.locator('.realism-controls summary').click();
  await page.getByRole('button', { name: 'Макро ткани', exact: true }).click();
  await page.waitForTimeout(1500);
  await page.getByRole('combobox', { name: 'Режим просмотра' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'work/realism-ui/interface-macro.png' });
  const exportPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Экспорт PNG', exact: true }).click();
  await (await exportPromise).saveAs('work/realism-ui/ui-export.png');
  const screenshot = PNG.sync.read(fs.readFileSync('work/realism-ui/ui-export.png'));
  assert.ok(screenshot.width > 400 && screenshot.height > 400);
  assert.deepEqual(errors, []);
  fs.writeFileSync('work/realism-ui/checks.json', JSON.stringify({ import: true, saveV2: true, reopen: true, remove: true, macro: true, export: [screenshot.width, screenshot.height], errors }, null, 2));
  console.log('UI import/save/reopen/remove/macro/export passed.');
} finally { await browser.close(); }
